spring:
  application:
    name: research-paper-assistant

  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterWrite=30d

server:
  port: 8080

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,cache
  endpoint:
    health:
      show-details: always

# OpenAPI/Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Custom properties
app:
  features:
    use-mock-openai: true
    use-mock-arxiv: false
    enable-caching: true

  arxiv:
    base-url: https://export.arxiv.org/api/query
    pdf-base-url: https://arxiv.org/pdf/

  mock:
    delays:
      min-ms: 500
      max-ms: 2000

  #Gemini configuration
  gemini:
    api-key: ${GEMINI_API_KEY}
    model: gemini-1.5-flash
    max-tokens: 2048
    temperature: 0.7
    api-url: https://generativelanguage.googleapis.com/v1beta/models/

    # Keep OpenAI config for future
    openai:
      api-key: ${OPENAI_API_KEY:mock-key}
      model: gpt-3.5-turbo
      max-tokens: 2000