spring:
  application:
    name: research-paper-assistant

  profiles:
    active: dev

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterWrite=30d

server:
  port: 8080

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,cache
  endpoint:
    health:
      show-details: always

# OpenAPI/Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

# Custom properties
app:
  features:
    use-mock-ai: false
    use-mock-arxiv: false
    use-gemini-ai: false
    use-open-ai: true
    enable-caching: true

  arxiv:
    base-url: https://export.arxiv.org/api/query
    pdf-base-url: https://arxiv.org/pdf/

  mock:
    delays:
      min-ms: 500
      max-ms: 2000

  #Gemini configuration
  gemini:
    api-key: ${GEMINI_API_KEY}
    model: gemini-1.5-flash
    max-tokens: 2048
    temperature: 0.7
    api-url: https://generativelanguage.googleapis.com/v1beta/models/



    #OpenAI configuration
  openai:
    api-key: ${OPENAI_API_KEY}
    model: gpt-3.5-turbo
    max-tokens: 2000
    temperature: 0.7
    api-url: https://api.openai.com/v1/chat/completions

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
    instances:
      arxivService:
        base-config: default
        failure-rate-threshold: 50
      geminiService:
        base-config: default
        failure-rate-threshold: 70
  retry:
    instances:
      arxivRetry:
        max-attempts: 3
        wait-duration: 5s
  management:
    endpoints:
      web:
        exposure:
          include: circuit breakers,retries